services:
  pgdatabase:
    image: postgres:14.5
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "postgres"
    networks:
      - repbot
    volumes:
      - database:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    profiles:
      - default
      - app
  pgdatabase_unpersisted:
    image: postgres:14.5
    networks:
      - repbot
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "postgres"
    ports:
      - 5432:5432
    profiles:
      - unpersisted
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - repbot
    profiles:
      - app
    volumes:
      - ./config/:/app/config/

volumes:
  database:

networks:
  repbot:

